-- models/marts/dim_listings.sql
WITH listings AS (
    SELECT
        id AS listing_id,
        name AS listing_name,
        description,
        neighborhood_overview,
        picture_url,
        property_type,
        property_type_std,
        room_type,
        accommodates,
        bathrooms_text,
        bathrooms,
        bedrooms,
        beds,
        amenities,
        amenity_count,
        has_wifi,
        has_kitchen,
        has_parking,
        has_ac,
        has_washer,
        has_tv,
        has_elevator,
        has_pool,
        has_gym,
        has_hot_tub,
        has_breakfast,
        is_pet_friendly,
        has_long_term_stays,
        has_self_checkin,
        price,
        minimum_nights,
        maximum_nights,
        number_of_reviews,
        review_scores_rating,
        review_scores_accuracy,
        review_scores_cleanliness,
        review_scores_checkin,
        review_scores_communication,
        review_scores_location,
        review_scores_value,
        instant_bookable,
        host_id
    FROM {{ ref('stg_listings') }}
)

SELECT * FROM listings
